DROP TABLE PAZIENTE  CASCADE CONSTRAINTS;
DROP TABLE ASSISTENZA CASCADE CONSTRAINTS;
DROP TABLE PRESIDIO_MEDICO CASCADE CONSTRAINTS;
DROP TABLE NECESSITA CASCADE CONSTRAINTS;
DROP TABLE PERSONALE CASCADE CONSTRAINTS;
DROP TABLE INFERMIERE CASCADE CONSTRAINTS;
DROP TABLE OPERATORE_SOCIALE CASCADE CONSTRAINTS;
-------------------------------------------------------------------

--  PAZIENTE

CREATE TABLE PAZIENTE (
N_TESSANITARIA VARCHAR(20) PRIMARY KEY,
SESSO_PAZ CHAR(1),
ASLNA INTEGER NOT NULL,
DISTURBO VARCHAR(30) NOT NULL,
TEL_FORNITO VARCHAR(10) NOT NULL,
CHECK (ASLNA>0 AND ASLNA <6),
CHECK (SESSO_PAZ='M'OR SESSO_PAZ='F'));



--  PRESIDIO_MEDICO

CREATE TABLE PRESIDIO_MEDICO(
ID_PRODOTTO INTEGER PRIMARY KEY,
NOME_PRES VARCHAR(15) NOT NULL,
MODULO_DOSE NUMBER(5,2) NOT NULL,
MISURA_DOSE VARCHAR(2),
QUANT_PRESENTE NUMBER(6,2) NOT NULL,
QUANT_MINOBB NUMBER(6,2) NOT NULL,
CHECK (MODULO_DOSE>=0),
CHECK (QUANT_PRESENTE>=0),
CHECK (QUANT_MINOBB>=0));


--  PERSONALE

CREATE TABLE PERSONALE (
N_TESMEDICASA INTEGER PRIMARY KEY,
NOME_PERS VARCHAR(15) NOT NULL,
COGNOME_PERS VARCHAR(15) NOT NULL,
SESSO_PERS CHAR(1) NOT NULL,
CELL_AZIEND VARCHAR(10) UNIQUE NOT NULL,
AUTOMUNITO CHAR(1) NOT NULL,
CHECK( AUTOMUNITO = 'S' OR AUTOMUNITO = 'N'));


-- INFERMIERE

CREATE TABLE INFERMIERE (
N_TESMEDICASA INTEGER PRIMARY KEY,
SPECIALIZZAZIONE VARCHAR(20) NOT NULL,
CONSTRAINT FK_INFERMIERE FOREIGN KEY (N_TESMEDICASA) REFERENCES PERSONALE(N_TESMEDICASA));


-- OPERATORE_SOCIALE

CREATE TABLE OPERATORE_SOCIALE(
N_TESMEDICASA INTEGER PRIMARY KEY,
QUALIFICA VARCHAR(20) NOT NULL,
CONSTRAINT FK_OPERATORES FOREIGN KEY (N_TESMEDICASA) REFERENCES PERSONALE(N_TESMEDICASA));


-- TABELLA 9 - ASSISTENZA

CREATE TABLE ASSISTENZA (
ID_ASS INTEGER PRIMARY KEY,
N_TESSANITARIA VARCHAR(20) NOT NULL,
N_TESMEDICASA INTEGER,
TIPO_ASS VARCHAR(3) NOT NULL,
CURA VARCHAR(30)  NOT NULL,
INIZIO_ASS DATE NOT NULL,
FINE_ASS DATE NOT NULL,
CHECK (TIPO_ASS='ADI'OR TIPO_ASS='ADO'),
CONSTRAINT FK_PAZIENTE FOREIGN KEY (N_TESSANITARIA) REFERENCES PAZIENTE(N_TESSANITARIA),
CONSTRAINT FK_PERSONALE FOREIGN KEY (N_TESMEDICASA) REFERENCES PERSONALE(N_TESMEDICASA));


-- TABELLA 10 - NECESSITA (ASSOCIAZIONE N-M TABELLE: ASSISTENZA - PRESIDIO_MEDICO)

CREATE TABLE NECESSITA(
ID_ASS INTEGER NOT NULL, 
ID_PRODOTTO INTEGER NOT NULL,
QUANTITA_PREL INTEGER NOT NULL,
CHECK(QUANTITA_PREL>=0),
CONSTRAINT PK_NECESSITA PRIMARY KEY (ID_ASS, ID_PRODOTTO),
CONSTRAINT FK_NECESSITA1 FOREIGN KEY (ID_ASS) REFERENCES ASSISTENZA(ID_ASS),
CONSTRAINT FK_NECESSITA2 FOREIGN KEY (ID_PRODOTTO) REFERENCES PRESIDIO_MEDICO(ID_PRODOTTO)) ;


                                                                              ALTER SESSION SET NLS_LANGUAGE=Italian; 

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24.MI';
                                                                              
-----------------------------------------------------------------------



