--DB FILATELIA
DROP TABLE AUTORI;
DROP TABLE BANCONOTE;
DROP TABLE MONETE;
DROP TABLE FRANCOBOLLI;
DROP TABLE OGGETTO;
DROP TABLE ACQUISTO;
DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
LOGIN 		VARCHAR2(15) PRIMARY KEY,
NOME			VARCHAR2(50),
COGNOME		VARCHAR2(50),
ETA				NUMBER(3),
SESSO			CHAR(1),
PASSWORD	VARCHAR2(16)
);


CREATE TABLE ACQUISTO(
ID 				NUMBER(10) PRIMARY KEY,
SCONTO		NUMBER(2),
DATA			DATE,
LOGIN			VARCHAR2(15) NOT NULL,
CONSTRAINT FK_LOGIN FOREIGN KEY (LOGIN) REFERENCES CLIENTE(LOGIN)
);

CREATE TABLE OGGETTO(
ID_OGG			NUMBER(10) PRIMARY KEY,
PROVENIENZA	VARCHAR2(50),
ANNO				NUMBER(4),
STATO_CONS	VARCHAR2(10),
TAGLIO			NUMBER,
PREZZO			NUMBER,
ID_ACQ			NUMBER(10) NOT NULL,
CONSTRAINT FK_ID_ACQ FOREIGN KEY (ID_ACQ) REFERENCES ACQUISTO(ID)
);

CREATE TABLE FRANCOBOLLI(
ID_OGG			NUMBER(10) PRIMARY KEY,
TIMBRATURA	CHAR(1),
DIMENSIONE	VARCHAR2(7),
CONSTRAINT FK_ID_OGG_F FOREIGN KEY (ID_OGG) REFERENCES OGGETTO(ID_OGG)
);

CREATE TABLE MONETE(
ID_OGG			NUMBER(10) PRIMARY KEY,
SERIE				VARCHAR2(20),
MATERIALE		VARCHAR2(30),
CONSTRAINT FK_ID_OGG_M FOREIGN KEY (ID_OGG) REFERENCES OGGETTO(ID_OGG)
);

CREATE TABLE BANCONOTE(
ID_OGG			NUMBER(10) PRIMARY KEY,
TEMA				VARCHAR2(50),
CONSTRAINT FK_ID_OGG_B FOREIGN KEY (ID_OGG) REFERENCES OGGETTO(ID_OGG)
);

CREATE TABLE AUTORI(
ID_OGG			NUMBER(10),
AUTORE			VARCHAR2(100),
CONSTRAINT PK_ID_OGG_A PRIMARY KEY (ID_OGG,AUTORE),
CONSTRAINT FK_ID_OGG_A FOREIGN KEY (ID_OGG) REFERENCES OGGETTO(ID_OGG)
);

