GRANT CONNECT, CREATE SESSION TO C##ADDESTRATORE;
GRANT SELECT ON REPARTO TO C##ADDESTRATORE;
GRANT SELECT ON CORSO_DI_ADDESTRAMENTO TO C##ADDESTRATORE;
GRANT SELECT ON SI_ISCRIVE TO C##ADDESTRATORE;
GRANT SELECT ON ADDESTRATORE TO C##ADDESTRATORE;
GRANT SELECT ON VETERINARIO TO C##ADDESTRATORE;

GRANT SELECT, INSERT, UPDATE, DELETE ON SI_ISCRIVE TO C##ADDESTRATORE;

GRANT SELECT ON ISCRIZIONI_CORSI TO C##ADDESTRATORE;

GRANT CREATE VIEW TO C##ADDESTRATORE;

GRANT CREATE PROCEDURE TO C##ADDESTRATORE;




