GRANT CONNECT, CREATE SESSION TO C##VET;
GRANT SELECT ON ALLEVAMENTO TO C##VET;
GRANT SELECT ON PROVIENE_DA TO C##VET;
GRANT SELECT ON REPARTO TO C##VET;
GRANT SELECT ON PRODOTTO TO C##VET;
GRANT SELECT ON PRENOTAZIONE TO C##VET;


GRANT SELECT, INSERT, UPDATE, DELETE ON VISITA_VETERINARIO TO C##VET;

GRANT SELECT ON PRENOTAZIONI_VET TO C##VET;

GRANT CREATE VIEW TO C##VET;

GRANT CREATE PROCEDURE TO C##VET;





