GRANT CONNECT, CREATE SESSION TO C##DIPENDENTE;
GRANT SELECT ON ALLEVAMENTO TO C##DIPENDENTE;
GRANT SELECT ON PROVIENE_DA TO C##DIPENDENTE;
GRANT SELECT ON REPARTO TO C##DIPENDENTE;
GRANT SELECT ON FORNITORE TO C##DIPENDENTE;
GRANT SELECT ON CONSEGNA TO C##DIPENDENTE;
GRANT SELECT ON PRODOTTO TO C##DIPENDENTE;
GRANT SELECT ON ACQUISTO TO C##DIPENDENTE;
GRANT SELECT ON ACQUISTO_CONTIENE TO C##DIPENDENTE;
GRANT SELECT ON VINCITORE_LOTTERIA TO C##DIPENDENTE;
GRANT SELECT ON CONSEGNA_CONTIENE TO C##DIPENDENTE;
GRANT SELECT ON CORSO_DI_ADDESTRAMENTO TO C##DIPENDENTE;
GRANT SELECT ON SI_ISCRIVE TO C##DIPENDENTE;
GRANT SELECT ON ADDESTRATORE TO C##DIPENDENTE;
GRANT SELECT ON DIPENDENTE TO C##DIPENDENTE;
GRANT SELECT ON TURNI_DI_LAVORO TO C##DIPENDENTE;
GRANT SELECT ON E_PRESENTE TO C##DIPENDENTE;
GRANT SELECT ON VETERINARIO TO C##DIPENDENTE;
GRANT SELECT ON VISITA_VETERINARIO TO C##DIPENDENTE;
GRANT SELECT ON VISITA_PETCARE TO C##DIPENDENTE;
GRANT SELECT ON PROMOZIONE TO C##DIPENDENTE;
GRANT SELECT ON PROMOZIONE_RIGUARDA TO C##DIPENDENTE;
GRANT SELECT ON PRENOTAZIONE TO C##DIPENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTE TO C##DIPENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ANIMALE TO C##DIPENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADOTTA TO C##DIPENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RESTITUISCE TO C##DIPENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACQUISTO TO C##DIPENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACQUISTO_CONTIENE TO C##DIPENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON VISITA_PETCARE TO C##DIPENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRENOTAZIONE TO C##DIPENDENTE;

GRANT SELECT ON ANIMALI_DISPONIBILI TO C##DIPENDENTE;
GRANT SELECT ON PRENOTAZIONI_PETCARE TO C##DIPENDENTE;

GRANT EXECUTE ON CALCOLO_PUNTI TO C##DIPENDENTE

GRANT CREATE VIEW TO C##DIPENDENTE;
GRANT CREATE PROCEDURE TO C##DIPENDENTE;



