GRANT CONNECT, CREATE SESSION TO C##CLIENTE;
GRANT SELECT ON ALLEVAMENTO TO C##CLIENTE;
GRANT SELECT ON PROVIENE_DA TO C##CLIENTE;
GRANT SELECT ON REPARTO TO C##CLIENTE;
GRANT SELECT ON PRODOTTO TO C##CLIENTE;
GRANT SELECT ON CORSO_DI_ADDESTRAMENTO TO C##CLIENTE;
GRANT SELECT ON SI_ISCRIVE TO C##CLIENTE;
GRANT SELECT ON ADDESTRATORE TO C##CLIENTE;
GRANT SELECT ON VETERINARIO TO C##CLIENTE;
GRANT SELECT ON VISITA_VETERINARIO TO C##CLIENTE;
GRANT SELECT ON VISITA_PETCARE TO C##CLIENTE;
GRANT SELECT ON PROMOZIONE TO C##CLIENTE;
GRANT SELECT ON PROMOZIONE_RIGUARDA TO C##CLIENTE;
GRANT SELECT ON PRENOTAZIONE TO C##CLIENTE;

GRANT SELECT ON ANIMALI_DISPONIBILI TO C##CLIENTE;


GRANT CREATE VIEW TO C##CLIENTE;
GRANT CREATE PROCEDURE TO C##CLIENTE;



