CREATE USER C##DB_PETSHOP IDENTIFIED BY doglover111;
CREATE USER C##CLIENTE IDENTIFIED BY superclient222;
CREATE USER C##DIPENDENTE IDENTIFIED BY bestworkerever333;
CREATE USER C##ADDESTRATORE IDENTIFIED BY cesarmilan444;
CREATE USER C##VET IDENTIFIED BY cheaperdrhouse555;

GRANT ALL PRIVILEGES TO C##DB_PETSHOP;

GRANT CREATE ANY VIEW TO C##DB_PETSHOP;

GRANT CREATE ANY PROCEDURE TO C##DB_PETSHOP;





