-- ===============================
-- SCHEDULER - STIPENDI AUTOMATICI
-- ===============================

-- JOB CHE AUTOMATICAMENTE OGNI MESE ASSEGNA GLI STIPENDI AGLI IMPIEGATI RICHIAMANDO
-- LA PROCEDURA STIPENDI


BEGIN DBMS_SCHEDULER.CREATE_JOB (
    JOB_NAME => 'STIPENDI_AUTOMATIZED',
    JOB_TYPE => 'PLSQL_BLOCK',
    JOB_ACTION =>  '    
                        BEGIN
                            STIPENDI; 
                        END;
                    ',
    START_DATE => TO_DATE('01-JAN-2022','DD-MM-YYYY'), 
    REPEAT_INTERVAL => 'FREQ = MONTHLY',
    ENABLED => TRUE,
    COMMENTS => 'ASSEGNAZIONE AUTOMATICA STIPENDI'); 
END;

-- CANCELLAZIONE JOB DI STIPENDI_AUTOMATIZED
BEGIN
    DBMS_SCHEDULER.DROP_JOB ('STIPENDI_AUTOMATIZED');
END;



-- PROCEDURA UTILIZZATA. LA PROCEDURA È SALVATA NELLA CARTELLA PROCEDURE
/*
CREATE OR REPLACE PROCEDURE STIPENDI IS

    ULTIMO_STIPENDIO    NUMBER;
BEGIN
    
    FOR i IN (SELECT CF FROM DIPENDENTE) LOOP
    
    BEGIN
    
    SELECT MAX(TOTALE_STIPENDIO)  INTO ULTIMO_STIPENDIO
    FROM STIPENDIO
    WHERE CF_DIPENDENTE = (i.CF)
    GROUP BY CF_DIPENDENTE;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            ULTIMO_STIPENDIO := 900;
    END;
    
    INSERT INTO STIPENDIO (CF_DIPENDENTE,DATA_STIPENDIO,TOTALE_STIPENDIO) VALUES (i.CF,SYSDATE,ULTIMO_STIPENDIO);

    END LOOP;
END;
/
*/