CREATE OR REPLACE VIEW ANIMALI_DISPONIBILI AS
    SELECT CODICE_ANIMALE,SESSO,TIPO,RAZZA,REPARTO FROM ANIMALE 
    MINUS
    SELECT CODICE_ANIMALE,SESSO,TIPO,RAZZA,REPARTO FROM (
        SELECT AD.CODICE_ANIMALE,SESSO,TIPO,RAZZA,REPARTO FROM ADOTTA AD JOIN ANIMALE AN ON AD.CODICE_ANIMALE = AN.CODICE_ANIMALE
        MINUS 
        SELECT R.CODICE_ANIMALE,SESSO,TIPO,RAZZA,REPARTO FROM RESTITUISCE R JOIN ANIMALE AN ON R.CODICE_ANIMALE = AN.CODICE_ANIMALE
        );
