-- ===================
-- LOTTERIA FORTUNATA! √
-- ===================

/* Procedura che assegna in maniera randomica un premio ad un cliente pescato tra chi ha effettuato almeno 3 acquisti nel mese corrente */

CREATE OR REPLACE PROCEDURE LOTTERIA
IS
  CF_VINCITORE              CHAR(16);
  NOME_VINCITORE            CLIENTE.NOME%TYPE;
  COGNOME_VINCITORE         CLIENTE.COGNOME%TYPE;
  MESE_ATTUALE              VARCHAR2(10);
  ULTIMO_MESE               VARCHAR2(10);
BEGIN

/* Selezioniamo l'ultimo mese di vincita in una variabile  */

  BEGIN
  SELECT MESE_VINCITA INTO ULTIMO_MESE
    FROM VINCITORE_LOTTERIA
        WHERE ROWNUM = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      ULTIMO_MESE:= TO_DATE('01/01/1900','DD/MM/YYYY');
  END;

  SELECT TO_CHAR(SYSDATE,'MONTH') INTO MESE_ATTUALE
   FROM DUAL;

/* vogliamo che la procedura possa essere chiamata massimo una volta al mese */
  IF(MESE_ATTUALE = ULTIMO_MESE AND ULTIMO_MESE IS NOT NULL) THEN
     DBMS_OUTPUT.PUT_LINE ('VINCITA GIA EFFETTUATA QUESTO MESE. TORNARE IL MESE PROSSIMO');

  ELSE

  /* se la condizione è rispettata peschiamo randomicamente un cliente e lo inseriamo */
  
  SELECT CF_CLIENTE INTO CF_VINCITORE FROM 
  (SELECT CF_CLIENTE 
  FROM (SELECT CF_CLIENTE, COUNT(*) AS ACQUISTI_EFFETTUATI
    FROM ACQUISTO_TESSERA
      WHERE DATA_ACQUISTO >= SYSDATE - 30 
        GROUP BY CF_CLIENTE)
        WHERE ACQUISTI_EFFETTUATI > 3
        ORDER BY DBMS_RANDOM.RANDOM
  )
            WHERE ROWNUM = 1;
  
  
  SELECT NOME,COGNOME INTO NOME_VINCITORE,COGNOME_VINCITORE
   FROM CLIENTE 
    WHERE CF = CF_VINCITORE;

  INSERT INTO VINCITORE_LOTTERIA(NOME,COGNOME,CF_VINCITORE,MESE_VINCITA)
  VALUES(NOME_VINCITORE,COGNOME_VINCITORE,CF_VINCITORE,TO_CHAR(SYSDATE,'MONTH'));
  COMMIT;

  END IF;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20017,'NESSUN CLIENTE HA EFFETTUATO PIU DI 3 ACQUISTI QUESTO MESE :(');

END;
/ 