/*
    TRIGGER #12  
    TRIGGER CHE IMPEDISCE ASSUMERE UN LAVORATORE CON UNA ETA NON COMPRESA TRA 18 E 60 √
*/

/* 
TEST
INSERT INTO DIPENDENTE (NUMERO_REPARTO,CF,NOME,SECONDO_NOME,COGNOME,DATA_NASCITA,VIA,CIVICO,CAP,CITTA,SESSO,DATA_ASSUNZIONE,NUMERO_CELLULARE,EMAIL) VALUES (14,'2222222222222222','JACKIE',NULL,'CHAN',TO_DATE('19/02/1900','DD/MM/YYYY'),'DIAZ',20,'80038','POMIGLIANO D''ARCO','M',TO_DATE('01/01/2022','DD/MM/YYYY'),'3313308033','JACKIE@GMAIL.COM');
 */


CREATE OR REPLACE TRIGGER CHECK_ETA_TR
BEFORE INSERT OR UPDATE ON DIPENDENTE
FOR EACH ROW
DECLARE
  ETA                 NUMBER; 
  ETA_NO              EXCEPTION;
BEGIN

  ETA := ABS(MONTHS_BETWEEN(SYSDATE,:NEW.DATA_NASCITA))/12;

  IF(ETA < 18 OR ETA > 60) THEN 
  RAISE ETA_NO;
  END IF;

EXCEPTION 
  WHEN ETA_NO THEN
    RAISE_APPLICATION_ERROR(-20022, 'IL DIPENDENTE NON HA LA GIUSTA ETÀ PER ESSERE ASSUNTO');
END;
/