/* 
    TRIGGER #1
    TRIGGER CHE IMPEDISCE AD UN CLIENTE DI RESTITUIRE UN ANIMALE CHE NON HA MAI ADOTTATO O SE È PASSATO UN MESE√
*/

/* DISCLAIMER: è stata utilizzata la macro PRAGMA AUTONOMOUS_TRANSACTION in quanto il trigger esegue una query su se stesso
Da questo momento in poi eviterò di ribadire questo concetto per i trigger seguenti*/

--test
--INSERT INTO RESTITUISCE (CODICE_ANIMALE,DATA_RESTITUZIONE,RIMBORSO,CF_CLIENTE) VALUES ('253786364772',TO_DATE('22/03/2022','DD/MM/YYYY'),250,'SPSLRA02H54F839K');


CREATE OR REPLACE TRIGGER RESTITUISCE_TR
AFTER INSERT OR UPDATE ON RESTITUISCE 
FOR EACH ROW 

DECLARE 

    COD_ANIMALE         ANIMALE.CODICE_ANIMALE%TYPE;
    DATA_AD             DATE;
    TROPPO_TEMPO        EXCEPTION;
    PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
    SELECT CODICE_ANIMALE,DATA_ADOZIONE
      INTO COD_ANIMALE,DATA_AD
       FROM ADOTTA
        WHERE CODICE_ANIMALE = :NEW.CODICE_ANIMALE AND CF_CLIENTE = :NEW.CF_CLIENTE;

        IF(ABS(FLOOR(MONTHS_BETWEEN(SYSDATE,DATA_AD))) > 1)
        THEN RAISE TROPPO_TEMPO;
        END IF;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR (-20009, 'NON PUOI RESTITUIRE UN ANIMALE CHE NON HAI MAI ADOTTATO');

  WHEN TROPPO_TEMPO THEN
    RAISE_APPLICATION_ERROR (-20019, 'NON PUOI RESTITUIRE UN ANIMALE SE È PASSATO PIU DI UN MESE');

END
COMMIT;
/