/*
    TRIGGER #3

    TRIGGER CHE IMPEDISCE L'IMMISSIONE DI UNA DATA D'ADOZIONE DIVERSA DA QUELLA ODIERNA √
*/

/* test
INSERT INTO ADOTTA (CODICE_ANIMALE,DATA_ADOZIONE,PREZZO_ADOZIONE,CF_CLIENTE) VALUES ('111206770586',TO_DATE('15/01/2022','DD/MM/YYYY'),400,'DNSMTT00P23F839I');
 */

CREATE OR REPLACE TRIGGER DATA_ADOZIONE_TR
BEFORE INSERT OR UPDATE ON ADOTTA
FOR EACH ROW

BEGIN
    /*
        TRUNC TRONCA LA DATA IN UN FORMATO SPECIFICO. SE PARAMETRO INERENTE AL FORMATO È OMESSO ALLORA LA FUNZIONE TRONCA ORE, MINUTI E SECONDI LASCIANDO
        ESCLUSIVAMENTE LE INFORMAZIONI GG/MM/YYYY
    */
   IF (TRUNC (:NEW.DATA_ADOZIONE) < TRUNC(SYSDATE) OR TRUNC (:NEW.DATA_ADOZIONE) > TRUNC(SYSDATE)) 
    
    THEN
        :NEW.DATA_ADOZIONE := TRUNC(SYSDATE);
       
      DBMS_OUTPUT.PUT_LINE('LA DATA DI ADOZIONE INSERITA È ANTECEDENTE O SUCCESSIVA ALLA DATA ODIERNA. PER TANTO IL PARAMETRO È STATO SOSTITUITO CON: '||SYSDATE);
   END IF;

END
COMMIT;
/
