/*
    TRIGGER #4
    TRIGGER CHE IMPEDISCE AI DIPENDENTI CON MENO DI DUE ANNI DI ESPERIENZA DI RICEVERE PIÙ DI 1300 EURO DI STIPENDIO √
*/
-- test
/* UPDATE STIPENDIO
SET TOTALE_STIPENDIO= 2000
WHERE CF_DIPENDENTE='1111111111111111'; */

CREATE OR REPLACE TRIGGER POCA_ESPERIENZA_TR
AFTER INSERT OR UPDATE ON STIPENDIO
FOR EACH ROW

DECLARE

    POCA_ESPERIENZA     EXCEPTION;
    DATA_ASS_DIP        DATE;
    PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
    SELECT DATA_ASSUNZIONE INTO DATA_ASS_DIP
        FROM DIPENDENTE WHERE CF = :NEW.CF_DIPENDENTE;


    IF 
        TO_NUMBER(TO_CHAR(DATA_ASS_DIP,'YYYY')) > TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')) - 2  AND :NEW.TOTALE_STIPENDIO>1300
        THEN RAISE POCA_ESPERIENZA;

    END IF;

EXCEPTION
  WHEN POCA_ESPERIENZA THEN
    RAISE_APPLICATION_ERROR(-20011,'IL DIPENDETE NON HA RAGGIUNTO L ESPERIENZA MINIMA PER UN TALE STIPENDIO');

END
COMMIT;
/