/*
    TRIGGER #6
    TRIGGER CHE IMPEDISCE DI INSERIRE GLI ANIMALI IN UN REPARTO SBAGLIATO
*/

/* Se il reparto non è quello corretto gli animali vengono automaticamente inseriti nel reparto giusto*/

/* 
test
update animale
set reparto = 5
where codice_animale = '000000035770';
 */
 
CREATE OR REPLACE TRIGGER REPARTO_TR
BEFORE INSERT OR UPDATE ON ANIMALE 
FOR EACH ROW 

DECLARE
  REPARTO_SBAGLIATO     EXCEPTION;
BEGIN
  IF(:NEW.TIPO = 'CANE') THEN 
  IF (:NEW.REPARTO != 1 AND :NEW.REPARTO != 2 AND :NEW.REPARTO != 3) THEN
    :NEW.REPARTO := 1;
  DBMS_OUTPUT.PUT_LINE ('REPARTO CAMBIATO IN :'||:NEW.REPARTO);
  END IF;
  ELSIF (:NEW.TIPO = 'GATTO' AND :NEW.REPARTO != 4) THEN 
  :NEW.REPARTO := 4;
  DBMS_OUTPUT.PUT_LINE ('REPARTO CAMBIATO IN :'||:NEW.REPARTO);

  ELSIF (:NEW.TIPO = 'CONIGLIO' AND :NEW.REPARTO  != 5) THEN 
  :NEW.REPARTO := 5;
  DBMS_OUTPUT.PUT_LINE ('REPARTO CAMBIATO IN :'||:NEW.REPARTO);

  ELSIF (:NEW.TIPO = 'RETTILE' AND :NEW.REPARTO  != 6) THEN 
  :NEW.REPARTO := 6;
  DBMS_OUTPUT.PUT_LINE ('REPARTO CAMBIATO IN :'||:NEW.REPARTO);

  ELSIF (:NEW.TIPO = 'VOLATILE' AND :NEW.REPARTO  != 7) THEN 
  :NEW.REPARTO := 7;
  DBMS_OUTPUT.PUT_LINE ('REPARTO CAMBIATO IN :'||:NEW.REPARTO);

  ELSIF (:NEW.TIPO = 'PESCE' AND :NEW.REPARTO  != 8) THEN 
  :NEW.REPARTO := 8;
  DBMS_OUTPUT.PUT_LINE ('REPARTO CAMBIATO IN :'||:NEW.REPARTO);

  ELSIF (:NEW.TIPO = 'ANFIBIO' AND :NEW.REPARTO  != 12) THEN 
  :NEW.REPARTO := 12;
  DBMS_OUTPUT.PUT_LINE ('REPARTO CAMBIATO IN :'||:NEW.REPARTO);


  END IF;
END
COMMIT;
/
