/*
    TRIGGER #7   
    TRIGGER CHE IMPEDISCE A UNA PROMOZIONE DI EFFETTUARE UNO SCONTO ECCESSIVO
*/

/* Per sconto eccessivo intendiamo una promozione che non permetta un guadagno del 30% sul prodotto */

/* test
update promozione_riguarda 
set sconto_applicato = 0.99
where codice_prodotto = '67763013'; */

CREATE OR REPLACE TRIGGER PROMO_TR
AFTER INSERT OR UPDATE ON PROMOZIONE_RIGUARDA
FOR EACH ROW

DECLARE 
    SCONTO_ECCESSIVO            EXCEPTION;
    COSTO_ACQUISTO_PRODOTTO     PRODOTTO.COSTO_ACQUISTO%TYPE;
    PREZZO_PRODOTTO             PRODOTTO.PREZZO%TYPE;
    PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN 
    SELECT COSTO_ACQUISTO INTO COSTO_ACQUISTO_PRODOTTO
    FROM PRODOTTO 
    WHERE CODICE_PRODOTTO = :NEW.CODICE_PRODOTTO;

    SELECT PREZZO INTO PREZZO_PRODOTTO
    FROM PRODOTTO 
    WHERE CODICE_PRODOTTO = :NEW.CODICE_PRODOTTO;

    IF (PREZZO_PRODOTTO - PREZZO_PRODOTTO*(:NEW.SCONTO_APPLICATO) - COSTO_ACQUISTO_PRODOTTO <= COSTO_ACQUISTO_PRODOTTO + COSTO_ACQUISTO_PRODOTTO*0.3) THEN
      
        RAISE SCONTO_ECCESSIVO;
      
    END IF;    

EXCEPTION
  WHEN SCONTO_ECCESSIVO THEN
    RAISE_APPLICATION_ERROR (-20014, 'LO SCONTO EFFETTUATO NON PERMETTE UN MARGINE DI PROFITTO DEL 30%');

END
COMMIT;
/