/*
    TRIGGER #9   
    TRIGGER CHE IMPEDISCE L'ADOZIONE DI UN ANIMALE GIA ADOTTATO DA QUALCUN ALTRO √
*/

/* INSERT INTO ADOTTA (CODICE_ANIMALE,DATA_ADOZIONE,PREZZO_ADOZIONE,CF_CLIENTE) VALUES ('000000035781',TO_DATE('15/01/2022','DD/MM/YYYY'),400,'DNSMTT00P23F839I');
 */
CREATE OR REPLACE TRIGGER NON_DISPONIBILE_TR
AFTER INSERT OR UPDATE ON ADOTTA
FOR EACH ROW
DECLARE
    CA              ANIMALE.CODICE_ANIMALE%TYPE;
    NON_DISP        EXCEPTION;
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    
    SELECT CODICE_ANIMALE INTO CA
    FROM (
    SELECT CF_CLIENTE,CODICE_ANIMALE FROM ADOTTA
    MINUS
    SELECT CF_CLIENTE, CODICE_ANIMALE FROM RESTITUISCE
    ) WHERE CODICE_ANIMALE = :NEW.CODICE_ANIMALE;

    IF (CA IS NOT NULL) THEN
       RAISE NON_DISP;

    END IF;
        
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        NULL;
    
    WHEN NON_DISP THEN 
        RAISE_APPLICATION_ERROR(-20017,'ANIMALE NON DISPONIBILE :( . . . GIA ADOTTATO DA QUALCUN ALTRO!');
    
END;
/